export const menuData = [
  {
    label: "Opcion 1",
    to: "/",
    icon: "pi pi-fw pi-home",
    items: [
      { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
    ],
  },
  {
    label: "Opcion 2",
    to: "/",
    icon: "pi pi-fw pi-home",
    items: [
      { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
    ],
  },
  {
    label: "Opcion 3",
    to: "/",
    icon: "pi pi-fw pi-home",
    items: [
      { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
      { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
    ],
  },
  {
    label: "",
    items: [
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
      {
        label: "Opcion n",
        icon: "pi pi-fw pi-bookmark",
        to: "/",
        items: [
          { label: "Portada", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Ranking", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Calendario", icon: "pi pi-fw pi-home", to: "/" },
          { label: "Atletas", icon: "pi pi-fw pi-home", to: "/" },
        ],
      },
    ],
  },
];
