export const TopSectionService = {
  getTopSectionData() {
    return [
      {
        id: "1000",
        code: "f230fh0g3",
        prueba: "100 mts",
        description: "Product Description",
        image: "bamboo-watch.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 24,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "400mts",
        code: "nvklal433",
        prueba: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 61,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        prueba: "Salto Largo",
        description: "Product Description",
        image: "blue-band.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
      },
      {
        id: "1003",
        code: "244wgerg2",
        prueba: "Salto Alto",
        description: "Product Description",
        image: "blue-t-shirt.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 25,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1004",
        code: "h456wer53",
        prueba: "Tiro de bala",
        description: "Product Description",
        image: "bracelet.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 73,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1005",
        code: "av2231fwg",
        prueba: "20 km Marcha",
        description: "Product Description",
        image: "brown-purse.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
      },
      {
        id: "1006",
        code: "bib36pfvm",
        prueba: "50 km Marcha",
        description: "Product Description",
        image: "chakra-bracelet.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 5,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        prueba: "Galaxy Earrings",
        description: "Product Description",
        image: "galaxy-earrings.jpg",
        fecha: "03/27",
        lugar: "Estadio O. Atahualpa",
        quantity: 23,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1008",
        code: "vbb124btr",
        prueba: "Game Controller",
        description: "Product Description",
        image: "game-controller.jpg",
        fecha: 99,
        lugar: "Estadio O. Atahualpa",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 4,
      },
      {
        id: "1009",
        code: "cm230f032",
        prueba: "Gaming Set",
        description: "Product Description",
        image: "gaming-set.jpg",
        fecha: 299,
        lugar: "Electronics",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 3,
      },
      {
        id: "1010",
        code: "plb34234v",
        prueba: "Gold Phone Case",
        description: "Product Description",
        image: "gold-phone-case.jpg",
        fecha: 24,
        lugar: "Accessories",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
      },
      {
        id: "1011",
        code: "4920nnc2d",
        prueba: "Green Earbuds",
        description: "Product Description",
        image: "green-earbuds.jpg",
        fecha: 89,
        lugar: "Electronics",
        quantity: 23,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1012",
        code: "250vm23cc",
        prueba: "Green T-Shirt",
        description: "Product Description",
        image: "green-t-shirt.jpg",
        fecha: 49,
        lugar: "Clothing",
        quantity: 74,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1013",
        code: "fldsmn31b",
        prueba: "Grey T-Shirt",
        description: "Product Description",
        image: "grey-t-shirt.jpg",
        fecha: 48,
        lugar: "Clothing",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 3,
      },
      {
        id: "1014",
        code: "waas1x2as",
        prueba: "Headphones",
        description: "Product Description",
        image: "headphones.jpg",
        fecha: 175,
        lugar: "Electronics",
        quantity: 8,
        inventoryStatus: "LOWSTOCK",
        rating: 5,
      },
      {
        id: "1015",
        code: "vb34btbg5",
        prueba: "Light Green T-Shirt",
        description: "Product Description",
        image: "light-green-t-shirt.jpg",
        fecha: 49,
        lugar: "Clothing",
        quantity: 34,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1016",
        code: "k8l6j58jl",
        prueba: "Lime Band",
        description: "Product Description",
        image: "lime-band.jpg",
        fecha: 79,
        lugar: "Fitness",
        quantity: 12,
        inventoryStatus: "INSTOCK",
        rating: 3,
      },
      {
        id: "1017",
        code: "v435nn85n",
        prueba: "Mini Speakers",
        description: "Product Description",
        image: "mini-speakers.jpg",
        fecha: 85,
        lugar: "Clothing",
        quantity: 42,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1018",
        code: "09zx9c0zc",
        prueba: "Painted Phone Case",
        description: "Product Description",
        image: "painted-phone-case.jpg",
        fecha: 56,
        lugar: "Accessories",
        quantity: 41,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
      {
        id: "1019",
        code: "mnb5mb2m5",
        prueba: "Pink Band",
        description: "Product Description",
        image: "pink-band.jpg",
        fecha: 79,
        lugar: "Fitness",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1020",
        code: "r23fwf2w3",
        prueba: "Pink Purse",
        description: "Product Description",
        image: "pink-purse.jpg",
        fecha: 110,
        lugar: "Accessories",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
      },
      {
        id: "1021",
        code: "pxpzczo23",
        prueba: "Purple Band",
        description: "Product Description",
        image: "purple-band.jpg",
        fecha: 79,
        lugar: "Fitness",
        quantity: 6,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
      },
      {
        id: "1022",
        code: "2c42cb5cb",
        prueba: "Purple Gemstone Necklace",
        description: "Product Description",
        image: "purple-gemstone-necklace.jpg",
        fecha: 45,
        lugar: "Accessories",
        quantity: 62,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1023",
        code: "5k43kkk23",
        prueba: "Purple T-Shirt",
        description: "Product Description",
        image: "purple-t-shirt.jpg",
        fecha: 49,
        lugar: "Clothing",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 5,
      },
      {
        id: "1024",
        code: "lm2tny2k4",
        prueba: "Shoes",
        description: "Product Description",
        image: "shoes.jpg",
        fecha: 64,
        lugar: "Clothing",
        quantity: 0,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1025",
        code: "nbm5mv45n",
        prueba: "Sneakers",
        description: "Product Description",
        image: "sneakers.jpg",
        fecha: 78,
        lugar: "Clothing",
        quantity: 52,
        inventoryStatus: "INSTOCK",
        rating: 4,
      },
      {
        id: "1026",
        code: "zx23zc42c",
        prueba: "Teal T-Shirt",
        description: "Product Description",
        image: "teal-t-shirt.jpg",
        fecha: 49,
        lugar: "Clothing",
        quantity: 3,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
      },
      {
        id: "1027",
        code: "acvx872gc",
        prueba: "Yellow Earbuds",
        description: "Product Description",
        image: "yellow-earbuds.jpg",
        fecha: 89,
        lugar: "Electronics",
        quantity: 35,
        inventoryStatus: "INSTOCK",
        rating: 3,
      },
      {
        id: "1028",
        code: "tx125ck42",
        prueba: "Yoga Mat",
        description: "Product Description",
        image: "yoga-mat.jpg",
        fecha: 20,
        lugar: "Fitness",
        quantity: 15,
        inventoryStatus: "INSTOCK",
        rating: 5,
      },
    ];
  },
};
